image: "node:10.7.0"

before_script:
  - npm install -g vsce

package:
  script:
    - su node -c "npm install"
    - su node -c "npm run vscode:prepublish"
    - su node -c "vsce package"
  artifacts:
    paths:
      - emacs-extras-*.vsix
